//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDD_DIALOG                      101
#define IDI_MAIN                        102
#define IDD_DIALOG_COMPUTER             103
#define IDD_DIALOG_SERVICE              104
#define IDC_BTN_EXIT                    1000
#define IDC_LIST_SERVICES               1001
#define IDC_BTN_UPDATE                  1002
#define IDC_STATICCOMPUTER              1003
#define IDC_BTN_COMPUTER                1004
#define IDC_LIST_COMPUTER               1005
#define IDC_EDIT_SERVICE_TYPE           1007
#define IDC_EDIT_START_TYPE             1008
#define IDC_EDIT_ERROR_CONTROL          1009
#define IDC_EDIT_PATH_NAME              1010
#define IDC_EDIT_ORDER_GROUP            1011
#define IDC_EDIT_TAG_ID                 1012
#define IDC_EDIT_DEPENDENCIES           1013
#define IDC_EDIT_START_NAME             1014
#define IDC_EDIT_DISPLAY_NAME           1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
